wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.21
    framework: torch
    is_jupyter_run: false
    python_version: 3.7.12
batch_size:
  desc: null
  value: 100
cgan_nets:
  desc: null
  value: large_ni
cgan_spec:
  desc: null
  value:
    disc_network:
      activation: relu
      hidden_layers:
      - 128
      - 128
      - 64
      - 64
      - 64
      - 64
      other_layers:
      - 64
      - 64
      type: double_track
      x_layers:
      - 64
      - 64
    gen_network:
      activation: relu
      hidden_layers:
      - 128
      - 128
      - 64
      - 64
      - 64
      - 64
      - 64
      - 64
      type: noise_injection
cgan_type:
  desc: null
  value: pearson
clip_grad:
  desc: null
  value: 0.0
cond_plot_trajectories:
  desc: null
  value: null
cond_scatter:
  desc: null
  value: null
config:
  desc: null
  value: config_files_active/insurance-mse.json
cpu:
  desc: null
  value: 0
dataset:
  desc: null
  value: real_insurance
disc_lr:
  desc: null
  value: null
disc_lr_decay:
  desc: null
  value: null
disc_optimizer:
  desc: null
  value: null
epochs:
  desc: null
  value: 1000
eval_batch_size:
  desc: null
  value: 1000
eval_cgan:
  desc: null
  value: null
eval_div:
  desc: null
  value: null
eval_samples:
  desc: null
  value: 200
gen_lr:
  desc: null
  value: null
gen_lr_decay:
  desc: null
  value: null
gen_optimizer:
  desc: null
  value: null
gen_samples:
  desc: null
  value: 1
gp_kernel:
  desc: null
  value: rbf
imp_samples:
  desc: null
  value: 500
kde_batch_size:
  desc: null
  value: 10
kde_val:
  desc: null
  value: 0
kernel_lr:
  desc: null
  value: 0.01
kernel_scale_max:
  desc: null
  value: 0.5
kernel_scale_min:
  desc: null
  value: 0.001
kernel_scales:
  desc: null
  value: 50
l2_reg:
  desc: null
  value: 0.0
log_coefficients:
  desc: null
  value: 0
lr:
  desc: null
  value: 0.0001
lr_decay:
  desc: null
  value: 1.0
mixture_comp:
  desc: null
  value: 5
mmd_lambda:
  desc: null
  value: 1.0
mmd_scales:
  desc: null
  value:
  - 1.0
  - 5.0
  - 10.0
  - 20.0
mmd_scales_x:
  desc: null
  value: null
mmd_scales_y:
  desc: null
  value: null
mode_find_lr:
  desc: null
  value: 0.01
mode_find_steps:
  desc: null
  value: 100
model:
  desc: null
  value: cganmse
name:
  desc: null
  value: cganmse-real_insurance-10-21
network:
  desc: null
  value: null
noise_dim:
  desc: null
  value: 1
noise_dist:
  desc: null
  value: gaussian
opt_restarts:
  desc: null
  value: 0
optimizer:
  desc: null
  value: adam
plot_dctd_modes:
  desc: null
  value: 0
plot_functions:
  desc: null
  value: 0
plot_gt:
  desc: null
  value: 0
plot_pdf:
  desc: null
  value: null
plot_pdf_index:
  desc: null
  value: null
plot_prefix:
  desc: null
  value: null
plot_trajectories:
  desc: null
  value: 20
proposal_scales:
  desc: null
  value:
  - 0.5
  - 1.0
  - 5.0
restore:
  desc: null
  value: null
restore_file:
  desc: null
  value: null
scatter:
  desc: null
  value: 0
seed:
  desc: null
  value: 42
sqrt_loss:
  desc: null
  value: 1
test:
  desc: null
  value: 1
test_runs:
  desc: null
  value: 10
train:
  desc: null
  value: 1
val_interval:
  desc: null
  value: 20
x_dim:
  desc: null
  value: 48
y_dim:
  desc: null
  value: 1
